### PR TITLE
fix(auth): Log out user if session has expired MAASENG-1414

### LINKED ISSUE #864: Investigate why session never expires, i.e. users never need to log back in
Could be something to do with the websocket connection, so the session never becomes inactive.

### PR DESCRIPTION
**Pull request by ndv99**
## Done

- Added `sessionExpired` to status state
- Set authenticated to false if session expires
- Add info notification on login screen if session expires
- Add warning message on session timeout page to inform users that session will expire if timeout length changed

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to `/settings/security/session-timeout`
- Change the timeout to "5 minutes" and save
- Ensure you are logged out (may have to wait a few seconds)
- Log in
- Make yourself a coffee/tea/beverage of your choice
- Chill out until 5 minutes have passed
- Go back to your computer
- Ensure you are logged out

## Fixes

- Fixes https://warthogs.atlassian.net/browse/MAASENG-1414
- Fixes #864 

## Screenshots

image

image

### CODE REVIEW

File: src/app/base/sagas/websockets.ts [hunk 1]
```diff
@@ -370,7 +370,15 @@ export function* handleMessage(
         });
       }
     } else if (websocketEvent.type === "close") {
-      yield* put({ type: "status/websocketDisconnected" });
+      yield* put({
+        type: "status/websocketDisconnected",
+        payload:
+          "code" in websocketEvent &&
+          websocketEvent.code === 100 &&
```
Comment (sparkiegeek) [inline src/app/base/sagas/websockets.ts:377]:
```suggestion
          websocketEvent.code === 1000 &&
```

Comment (ndv99) [reply src/app/base/sagas/websockets.ts:377]: :facepalm: well spotted!

File: src/app/store/status/slice.ts [hunk 2]
```diff
@@ -125,8 +126,14 @@ const statusSlice = createSlice({
...
     },
-    websocketDisconnected: (state: StatusState) => {
+    websocketDisconnected: (
+      state: StatusState,
+      action: PayloadAction<StatusState["sessionExpired"]>
+    ) => {
       state.connected = false;
+      if (action.payload === true) {
+        state.authenticated = false;
+      }
```
Comment (petermakowski) [inline src/app/store/status/slice.ts:136]: As discussed during our session, let's move this to `websocketDisconnect` action.

File: src/app/store/status/slice.ts [hunk 3]
```diff
@@ -17,6 +17,7 @@ const statusSlice = createSlice({
     connecting: false,
     noUsers: false,
     error: null,
+    sessionExpired: false,
```
Comment (petermakowski) [inline src/app/store/status/slice.ts:20]: As discussed, let's remove and use authenticationError instead.

File: src/app/base/sagas/websockets.ts [hunk 4]
```diff
@@ -370,7 +370,15 @@ export function* handleMessage(
...
-      yield* put({ type: "status/websocketDisconnected" });
+      yield* put({
+        type: "status/websocketDisconnected",
+        payload:
+          "code" in websocketEvent &&
+          websocketEvent.code === 1000 &&
+          websocketEvent.reason === "Session expired"
+            ? true
+            : false,
+      });
```
Comment (petermakowski) [inline src/app/base/sagas/websockets.ts:381]: As discussed, let's add `{ code, reason}` to action payload directly.

File: src/app/utils/timeSpan.ts [hunk 5]
```diff
@@ -42,7 +42,7 @@ export const timeSpanToMinutes = (timeSpan: TimeSpan | null): Minutes =>
   durationToMinutes(timeSpanToDuration(timeSpan));
 
 export const secondsToDuration = (seconds: number | undefined): Duration => {
-  const now = new Date();
+  const now = new Date().getUTCDate();
```
Comment (petermakowski) [inline src/app/utils/timeSpan.ts:45]: Good spot!!

File: src/app/store/status/slice.ts [hunk 6]
```diff
@@ -117,15 +117,21 @@ const statusSlice = createSlice({
...
+      if (
+        action.payload.code === 1000 &&
+        action.payload.reason === "Session expired"
+      ) {
+        state.authenticated = false;
+        state.authenticationError = action.payload.reason;
+      }
     },
     websocketDisconnected: (state: StatusState) => {
+      // debugger;
```
Comment (petermakowski) [inline src/app/store/status/slice.ts:134]: 👀

File: src/app/App.tsx [hunk 7]
```diff
@@ -82,7 +83,19 @@ export const App = (): JSX.Element => {
...
+          <Notification severity="information">
+            Your session has expired. Please log in again to continue using
+            MAAS.
+          </Notification>
+          <Login />
+        </MainContentSection>
+      );
+    } else {
+      content = <Login />;
+    }
```
[the remark this answers is not in the document]
Comment (ndv99) [reply src/app/App.tsx:98]: Can do, yeah.

As for the `MainContentSection`, I was just wrapping it here so that the notification displays in a way that matches Amy's designs, the original <Login /> wasn't warpped so I was just keeping it consistent witht hat, but I can change it

[the remark this answers is not in the document]
Comment (petermakowski) [reply src/app/App.tsx:98]: Yes please, thanks!

**Comment by petermakowski** [comment]
@ndv99  As discussed, the app breaks if you enter invalid login credentials. Might be worth adding an e2e test for that as well.

**Review by petermakowski — APPROVED** [review]
LGTM, authentication errors handling could use some work, but this needs some more thought. Let's work on this separately.

File: src/app/App.tsx [hunk 8]
```diff
@@ -82,7 +83,31 @@ export const App = (): JSX.Element => {
...
+      <MainContentSection>
+        {authenticationError ? (
+          authenticationError === "Session expired" ? (
+            <Notification severity="information">
+              Your session has expired. Plese log in again to continue using
+              MAAS.
+            </Notification>
+          ) : (
+            <Notification severity="negative" title="Error">
+              {typeof authenticationError === "string" ? (
```
[the remark this answers is not in the document]
Comment (ndv99) [reply src/app/App.tsx:96]: Sounds good to me, thanks. We'll look into it either tomorrow or next week
