### PR TITLE
fix(settings): Update MAAS name example emotes to not be misleading #4785

### LINKED ISSUE #4785: "Examples: :no_entry: maas-prod" is misleading
**Describe the bug**

In the MAAS config, there is a section about examples you can use as "MAAS name".

> Examples:
> ⛔ maas-prod
> my-maas ⚠️ no-deploys

I initially thought that I cannot use `maas-prod` as my MAAS name since it was prefixed with the `⛔` sign and wondered why I cannot use `maas-prod` which totally looks valid.

I know what those examples mean by now, but in any case, `⛔` and `⚠️` are usually the last symbols we want to see in a software UI in general because it suggests a system error or a warning we need to handle whenever we see it.

Again, I know what the examples mean but there may be better examples than those.

https://github.com/canonical/maas-ui/blob/8f974413d0a8dc2a13654042bad614fc620cdeb7/src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx#L123-L124

**maas-ui version**
maas-ui 3.3.0 acde9f13b45dd515b3d9638545bf82d282d7d5a2

^^^ on a side note, this version was hard to find since there is no instruction in the bug report template.

**MAAS version**
3.3.0-13159-g.1c22f7beb-0ubuntu1~22.04.1

**LP issue**
N/A

**To Reproduce**

**Expected behavior**

**Screenshots**

Screenshot from 2023-02-24 15-53-54

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by ndv99**
## Done

- Updated MAAS name emoji examples in configuration to not be misleading

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to `/settings/configuration/general`
- Ensure emotes match the "after" screenshot below

## Fixes

Fixes #4785 

## Backports

Will be backported to 3.3 once merged

### Before
image

### After
image

### CODE REVIEW

File: src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx [hunk 1]
```diff
@@ -120,8 +120,9 @@ const GeneralForm = (): JSX.Element => {
             Use MAAS name and unicode emoji(s) to describe your MAAS instance.{" "}
             <br />
             <br />
-            Examples: <br />⛔ maas-prod <br />
-            my-maas ⚠️ no-deploys
+            Examples: <br />
+            US-west-2🇺🇸MAAS-prod <br />
+            my-maas❗no-deploys
```
Comment (petermakowski) [inline src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx:125]: Missing space (according to [original suggestion](https://github.com/canonical/maas-ui/issues/4785#issuecomment-1446201400))
```suggestion
            US-west-2 🇺🇸 MAAS-prod <br />
            my-maas ❗ no-deploys
```

Comment (ndv99) [reply src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx:125]: Damn, I forgot that we *can* have spaces for MAAS names!

**Review by petermakowski — APPROVED** [review]
